#!/usr/bin/env bash
# Stop 4-to_infinity_and_beyond process

pid=$(pgrep -f 4-to_infinity_and_beyond)

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond with PID $pid has been stopped."
else
    echo "Process 4-to_infinity_and_beyond not found."
fi

