#!/usr/bin/env bash
#comit
while true; do
    if [ -f /tmp/stop_infinity ]; then
        echo "Terminated"
        rm -f /tmp/stop_infinity
        exit 0
    fi
    echo "To infinity and beyond"
    sleep 2
done

