#!/bin/bash
# 67-stop_me_if_you_can
# Sends SIGTERM to the 7-highlander process

# Find the PID of 7-highlander
pid=$(pgrep -f 7-highlander)

if [ -n "$pid" ]; then
    # Send SIGTERM
    kill -TERM "$pid"
else
    echo "7-highlander process not found."
fi

