#!/bin/bash
# 7-highlander
# Prints "To infinity and beyond" indefinitely
# Prints "I am invincible!!!" when receiving SIGTERM

# Trap the SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

