#!/usr/bin/env bash
# Sends SIGKILL to 7-highlander

pid=$(pgrep -f 7-highlander)

if [ -n "$pid" ]; then
    kill -9 "$pid"
    echo "7-highlander process with PID $pid has been killed."
else
    echo "7-highlander process not found."
fi

